export { appointmentsRoute } from './appointments/appointments'
export { contactsRoute } from './contacts/contacts'
export { calendarRoute } from './calendar/calendar'
export { eventFormRoute } from './events/eventForm'
export { eventsRoute } from './events/events'
export { loginRoute } from './login/login'
export { noMatchRoute } from './noMatch/noMatch'
