name: Build

permissions:
  pull-requests: write

on:
  pull_request:
    branches:
      - '*'     # Listen to all branches
    types:
      - opened
      - synchronize
  push:
    branches:
      - master
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: lts

      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn run build