name: Cypress Tests

on:
  pull_request:
    branches:
      - '*'
    types:
      - opened
      - synchronize
  push:
    branches:
      - master
      - develop

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Wait for successful build
        uses: lewagon/wait-on-check-action@v1.3.3
        with:
          ref: ${{ github.ref }}
          check-name: 'Build'
          repo-token: ${{ secrets.ACCESS_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: yarn dev --mode staging
          wait-on: http://localhost:5173
          record: true
          parallel: true
        env:
          CYPRESS_SUPABASE_URL: ${{ secrets.CYPRESS_SUPABASE_URL }}
          CYPRESS_SUPABASE_SERVICE_KEY: ${{ secrets.CYPRESS_SUPABASE_SERVICE_KEY }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_KEY: ${{ secrets.VITE_SUPABASE_KEY }}