name: Lint

permissions:
  pull-requests: write

on:
  pull_request:
    branches:
      - '*'     # Listen to all branches
    types:
      - opened
      - synchronize
  push:
    branches:
      - master
      - develop

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Code Linting
        run: yarn run lint:report
        continue-on-error: true
      
      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          report-json: "eslint_report.json"