name: Lint

permissions:
  pull-requests: write

on: [pull_request]

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Code Linting
        run: yarn run lint:report
        continue-on-error: true
      
      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@v3
        with:
          report-json: "eslint_report.json"