name: Tests

permissions:
  pull-requests: write

on:
  pull_request:
    branches:
      - '*'
    types:
      - opened
      - synchronize
  push:
    branches:
      - master
      - develop

jobs:
  e2e:
    name: E2E tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          start: yarn dev
          wait-on: http://localhost:5173
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_KEY: ${{ secrets.VITE_SUPABASE_KEY }}