name: Unit Tests

permissions:
  pull-requests: write

on:
  pull_request:
    branches:
      - '*'     # Listen to all branches
    types:
      - opened
      - synchronize
  push:
    branches:
      - master
      - develop

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20.13.1'

      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Setup Env Variables
        run: |
          touch .env
          echo VITE_TEST_SUPABASE_URL=${{ secrets.VITE_TEST_SUPABASE_URL }} >> .env
          echo VITE_TEST_SUPABASE_KEY=${{ secrets.VITE_TEST_SUPABASE_KEY }} >> .env

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Unit Tests
        run: yarn run test
